[build]
rustflags = ["--cfg=delivery=\"direct\""]

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
rustflags = [
    "-C", "link-arg=-Wl,-rpath-link=/Users/olau/Workspace/labyrinth-server/linux/lib64",
    "-C", "link-arg=-Wl,-rpath-link=/Users/olau/Workspace/labyrinth-server/linux/usr/lib64",
    "-C", "link-arg=-static",
    "-C", "link-arg=-L/Users/olau/Workspace/labyrinth-server/linux/lib64",
    "-C", "link-arg=-L/Users/olau/Workspace/labyrinth-server/linux/usr/lib64",
    "-C", "link-arg=-lc",
#    "-C", "link-arg=-lpthread",
    "-C", "link-arg=-ldl"
]
